# Travel Theme Configuration - 绝区零风格

# 基本设置
default_cover_image: img/background.jpg
default_post_title: '无标题文档'
url_root: '/'
favicon: /favicon.ico
logo: /images/logo.png

# 导航菜单
menu:
  '首页': /
  '分类': /categories/
  '标签': /tags/
  '关于': /about/
  '友链': /links/


# 社交媒体
media:
  - icon: iconfont icon-github
    link: 'https://github.com/harkerhand'
    tip: 'GitHub'
  - icon: iconfont icon-mail
    link: 'mailto:contact@example.com'
    tip: '邮箱'
  - icon: iconfont icon-game
    link: 'https://zenless.hoyoverse.com/'
    tip: '绝区零官网'

# 用户信息卡片配置
author_info:
  avatar: /img/logo_circle.png
  level: 60
  exp_current: 114514
  exp_total: 9999999
  exp_percentage: 11.45

# 图标字体
iconfont:
  - //at.alicdn.com/t/c/font_1736178_k526ubmyhba.css
  - //at.alicdn.com/t/c/font_4823232_6grnmuy6d4c.css
  - //at.alicdn.com/t/c/font_1749284_5i9bdhy70f8.css

# 自定义CSS和JS
custom_css:
custom_js:

# 代码块配置
code:
  copy_btn: true
  language:
    enable: true
    default: "TEXT"
  highlight:
    enable: true
    line_number: true

# 图片功能
image_zoom:
  enable: true
  img_url_replace: ['', '']

image_caption:
  enable: true

# 懒加载
lazyload:
  enable: true
  loading_img: /images/loading.gif
  onlypost: false
  offset_factor: 2

# 搜索功能
search:
  enable: true
  path: /local-search.xml
  field: post
  content: true

# 首页配置
index:
  # 瀑布流布局
  waterfall: true
  # 每页文章数
  per_page: 10
  # 文章摘要长度
  excerpt_length: 200
  # 首页Banner图
  banner_img: img/background.jpg
  banner_img_height: 100


# 文章配置
post:
  banner_img: img/background.jpg
  banner_img_height: 70
  banner_mask_alpha: 0.3
  
  # 相关文章
  related_posts:
    enable: true
    limit: 5
  
  # 上下文章导航
  prev_next: true
  
  # 文章目录
  toc:
    enable: true
    placement: right
    auto_open: true
    headingSelector: "h1,h2,h3,h4,h5,h6"
    collapseDepth: 0
  
  # 文章元信息
  meta:
    author:
      enable: true
    date:
      enable: true
      format: "LL a"
    wordcount:
      enable: true
    min2read:
      enable: true
      awl: 2
      wpm: 60
    views:
      enable: false
      source: "busuanzi"

# 关于页
about:
  enable: true
  title: "关于"
  subtitle: "关于我"
  banner_img: img/background.jpg
  banner_img_height: 60
  name: "ZZZ Blog"
  intro: "一个绝区零风格的博客主题"
  avatar: img/logo_circle.png
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/harkerhand", tip: "GitHub" }
    - { class: "iconfont icon-mail", link: "mailto:harkerhand@outlook.com", tip: "邮箱" }

# 友链页
links:
  enable: true
  title: "友链"
  subtitle: "朋友们"
  banner_img: img/background.jpg
  banner_img_height: 60
  items:
    - { title: "Hexo", intro: "快速、简洁且高效的博客框架", link: "https://hexo.io", avatar: "/images/hexo.png" }
  onerror_avatar: img/logo_circle.png
  custom:
    enable: false
    content: ''

# 分类页
category:
  enable: true
  title: "分类"
  subtitle: "文章分类"
  banner_img: img/background.jpg
  banner_img_height: 60
  order_by: "-length"
  collapse_depth: 0
  post_order_by: "-date"
  post_limit: 10

# 标签页
tag:
  enable: true
  title: "标签"
  subtitle: "标签云"
  banner_img: img/background.jpg
  banner_img_height: 80
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"

# 404页面
page404:
  enable: true
  title: "页面未找到"
  subtitle: "抱歉，您访问的页面不存在"
  banner_img: img/background.jpg
  banner_img_height: 85
  banner_mask_alpha: 0.3
  redirect_delay: 5000

